language: generic

branches:
  except:
    - deps

dist: trusty
sudo: false

matrix:
  include:
    # 3 package variants on major Tcl releases mixed with 2 install variants
    # run tests in code coverage mode on first installation variant
    # for each Tcl releases
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.4 --prefix=/tmp/modules-tcl' MAKE_TESTCOVERAGE='y'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.4
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.5 --prefix=/tmp/modules-tcl' MAKE_TESTCOVERAGE='y'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.5
    # also enable a display on this test case to validate x-resource behavior
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.6 --prefix=/tmp/modules-tcl' MAKE_TESTCOVERAGE='y'
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3 # give xvfb some time to start
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.6

    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.4 --prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/modules/init/ --with-loadedmodules=null:dot'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.4
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.5 --prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/modules/init/ --with-loadedmodules=null:dot'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.5
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.6 --prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/modules/init/ --with-loadedmodules=null:dot'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.6


    # 1 package variation with environment-modules installed
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.6 --prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/modules/init/ --with-loadedmodules=null:dot'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - environment-modules
            - dejagnu
            - man-db
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.6

env:
  global:
    - RUNTESTFLAGS='-v'

install: true

script:
  - ./configure $CONFIGURE_OPTS
  - make
  - if [ "$MAKE_TESTCOVERAGE" = 'y' ]; then make testcoverage; fi
  - if [ "$MAKE_TESTCOVERAGE" != 'y' ]; then make test; fi
  - make install
  - make testinstall
  - make uninstall

# report code coverage results
after_success: |
  [ "$MAKE_TESTCOVERAGE" = 'y' ] &&
  contrib/nglfar2ccov modulecmd.tcl &&
  bash <(curl -s https://codecov.io/bash) -s coverage
